### PR TITLE
Added support for Bitbucket snippets to Keybase proofs.

### LINKED ISSUE #19: Add support for Bitbucket to Keybase
Atlassian Bitbucket [launched](https://blog.bitbucket.org/2015/03/18/snippets-for-teams-are-here-with-a-rich-set-of-apis/) their Snippets feature today which allows developers to post arbitrary pieces of code publicly. With the addition of this feature, users should now be able to create Bitbucket proofs.

Documentation for the API is available here: https://confluence.atlassian.com/display/BITBUCKET/snippets+Endpoint

### PR DESCRIPTION
**Pull request by mark-adams**
Atlassian Bitbucket [launched](https://blog.bitbucket.org/2015/03/18/snippets-for-teams-are-here-with-a-rich-set-of-apis/) their Snippets feature today which allows developers to post arbitrary pieces of code publicly. With the addition of this feature, users should now be able to create Bitbucket proofs.

I did my best to port the existing Github proof over to be compatible with Bitbucket, but I would appreciate your review of the attached proof for Bitbucket and any recommendations that you could make. I know there are several people who host their projects on Bitbucket that would love to have this in Keybase.

Documentation for their API is available here: https://confluence.atlassian.com/display/BITBUCKET/snippets+Endpoint

This resolves #19

### CODE REVIEW

**Comment by wbinnssmith** [comment]
:+1: this would be incredible!

**Comment by ostyn** [comment]
Woot woot!

**Comment by subvertallchris** [comment]
:+1:

**Comment by mark-adams** [comment]
Rebase to fix merge conflict... please review.

**Comment by mark-adams** [comment]
Yet again rebased to fix merge conflicts... Any chance I can get a review? @maxtaco?

**Comment by maxtaco** [comment]
Sorry again for the huge slowness on our part.  There are a few more U/X components that need to be designed around this too, and also integration with our new Go client that we just getting ready to push a test alpha out of next week. We're stretched pretty thin, but of course still want to make this happen.  Thanks for bearing with us.

**Comment by maxtaco** [comment]
Started some work on this merge tonight, need to figure out how our scraper can plug into their Oauth API.  Thanks again.

**Comment by mark-adams** [comment]
Sounds great!! Thanks for looking at it!

I'm actually a developer on the Bitbucket team, so if you have any questions, I'd be happy to answer them!

**Comment by mark-adams** [comment]
Your scraper should have a pretty easy time ingesting public snippets using [the snippets resources](https://confluence.atlassian.com/bitbucket/snippets-endpoint-719095086.html) in the REST API. Very similar to Github's gists.

Please let me know if I can be of any help!

**Comment by maxtaco** [comment]
Hmmm, looks like bitbucket has a very aggressive rate-limiter that prevents our "hunter" from working with an access token.

**Comment by maxtaco** [comment]
I'll go ahead and merge your PR and then work on top of it.  Thanks Mark!

**Comment by maxtaco** [comment]
(Still making changes over in #19)

**Pull request merged**
