### PR TITLE
wallet key support

### PR DESCRIPTION
**Pull request by maxtaco**
- looks a lot like a sibkey

```json
{
   "ctime" : 1520548117,
   "expire_in" : 157680000,
   "body" : {
      "key" : {
         "username" : "u_a0c0e0ebdd",
         "uid" : "8915d5377faeb99ad433606154b34d42",
         "kid" : "0120fccf218330b639cf243fbe0c9c784e08cba59ddd5dbfc41406b27d863bdad2980a",
         "host" : "keybase.io"
      },
      "type" : "wallet_key",
      "wallet_key" : {
         "reverse_sig" : "g6Rib2R5hqhkZXRhY2hlZMOpaGFzaF90eXBlCqNrZXnEIwEgKjXddgegujxgX6bWMQ3ETCR5IbpE/9rlQilWylUklycKp3BheWxvYWTFAbx7ImJvZHkiOnsia2V5Ijp7Imhvc3QiOiJrZXliYXNlLmlvIiwia2lkIjoiMDEyMGZjY2YyMTgzMzBiNjM5Y2YyNDNmYmUwYzljNzg0ZTA4Y2JhNTlkZGQ1ZGJmYzQxNDA2YjI3ZDg2M2JkYWQyOTgwYSIsInVpZCI6Ijg5MTVkNTM3N2ZhZWI5OWFkNDMzNjA2MTU0YjM0ZDQyIiwidXNlcm5hbWUiOiJ1X2EwYzBlMGViZGQifSwidHlwZSI6IndhbGxldF9rZXkiLCJ2ZXJzaW9uIjoxLCJ3YWxsZXRfa2V5Ijp7ImN1cnJlbmN5Ijoic3RlbGxhciIsImtpZCI6IjAxMjAyYTM1ZGQ3NjA3YTBiYTNjNjA1ZmE2ZDYzMTBkYzQ0YzI0NzkyMWJhNDRmZmRhZTU0MjI5NTZjYTU1MjQ5NzI3MGEiLCJyZXZlcnNlX3NpZyI6bnVsbH19LCJjdGltZSI6MTUyMDU0ODExNywiZXhwaXJlX2luIjoxNTc2ODAwMDAsInByZXYiOm51bGwsInNlcV90eXBlIjoxLCJzZXFubyI6MCwidGFnIjoic2lnbmF0dXJlIn2jc2lnxEDp7mlHzUdo+OzHxhU/0VIJ0Z0o6ZOvnx93JsfXUeJDMaNH2ECRFJvMJWPKYM0KUtzfR3Tdeh0RNujWTIhRf/IDqHNpZ190eXBlIKN0YWfNAgKndmVyc2lvbgE=",
         "kid" : "01202a35dd7607a0ba3c605fa6d6310dc44c247921ba44ffdae5422956ca552497270a",
         "currency" : "stellar"
      },
      "version" : 1
   },
   "seq_type" : 1,
   "tag" : "signature",
   "prev" : null,
   "seqno" : 0
}
```

### CODE REVIEW

**Comment by maxtaco** [comment]
Cc: @oconnor663

**Comment by maxtaco** [comment]
Make sure this is perfect, since we can never change it!

**Comment by patrickxb** [comment]
Shouldn't `body.wallet_key.kid` be of the form `GCKLHXC22HCGV52UOISFKYZQX7YIVDBPSZ7UUYDFK6URRR6VDRANPC5K`?

**Comment by maxtaco** [comment]
I was using our format, but presumably one can convert freely between the two.  How exactly?

**Comment by maxtaco** [comment]
Looks like that comes from [here](https://stellar.github.io/js-stellar-sdk/node_modules_stellar-base_src_strkey.js.html#line24).

We can convert pretty easily between the two. The advantage to this approach is that we don't have to source in a lot of new libraries in this library.

**Comment by maxtaco** [comment]
OK, here's an alternative:

```json
{
   "ctime" : 1520548117,
   "expire_in" : 157680000,
   "body" : {
      "key" : {
         "username" : "u_a0c0e0ebdd",
         "uid" : "8915d5377faeb99ad433606154b34d42",
         "kid" : "0120fccf218330b639cf243fbe0c9c784e08cba59ddd5dbfc41406b27d863bdad2980a",
         "host" : "keybase.io"
      },
      "type" : "wallet",
      "wallet_key" : {
         "reverse_sig" : "g6Rib2R5hqhkZXRhY2hlZMOpaGFzaF90eXBlCqNrZXnEIwEgKjXddgegujxgX6bWMQ3ETCR5IbpE/9rlQilWylUklycKp3BheWxvYWTFAbx7ImJvZHkiOnsia2V5Ijp7Imhvc3QiOiJrZXliYXNlLmlvIiwia2lkIjoiMDEyMGZjY2YyMTgzMzBiNjM5Y2YyNDNmYmUwYzljNzg0ZTA4Y2JhNTlkZGQ1ZGJmYzQxNDA2YjI3ZDg2M2JkYWQyOTgwYSIsInVpZCI6Ijg5MTVkNTM3N2ZhZWI5OWFkNDMzNjA2MTU0YjM0ZDQyIiwidXNlcm5hbWUiOiJ1X2EwYzBlMGViZGQifSwidHlwZSI6IndhbGxldF9rZXkiLCJ2ZXJzaW9uIjoxLCJ3YWxsZXRfa2V5Ijp7ImN1cnJlbmN5Ijoic3RlbGxhciIsImtpZCI6IjAxMjAyYTM1ZGQ3NjA3YTBiYTNjNjA1ZmE2ZDYzMTBkYzQ0YzI0NzkyMWJhNDRmZmRhZTU0MjI5NTZjYTU1MjQ5NzI3MGEiLCJyZXZlcnNlX3NpZyI6bnVsbH19LCJjdGltZSI6MTUyMDU0ODExNywiZXhwaXJlX2luIjoxNTc2ODAwMDAsInByZXYiOm51bGwsInNlcV90eXBlIjoxLCJzZXFubyI6MCwidGFnIjoic2lnbmF0dXJlIn2jc2lnxEDp7mlHzUdo+OzHxhU/0VIJ0Z0o6ZOvnx93JsfXUeJDMaNH2ECRFJvMJWPKYM0KUtzfR3Tdeh0RNujWTIhRf/IDqHNpZ190eXBlIKN0YWfNAgKndmVyc2lvbgE=",
         "kid" : "01202a35dd7607a0ba3c605fa6d6310dc44c247921ba44ffdae5422956ca552497270a",
      },
      "wallet" : {
         "currency" : "stellar",
         "address" : "GCKLHXC22HCGV52UOISFKYZQX7YIVDBPSZ7UUYDFK6URRR6VDRANPC5K"
      },
      "version" : 1
   },
   "seq_type" : 1,
   "tag" : "signature",
   "prev" : null,
   "seqno" : 0
}
```

In this model, the caller should pass in a stellar-style address, and we'd convert to a keybase-style KID, so we can use the signature machinery inside the proofs class. It would mean taking on some dependencies.

**Comment by maxtaco** [comment]
Sigh:

```
keybase-proofs@2.1.30 /Users/max/src/keybase/proofs
└─┬ stellar-sdk@0.8.0 
  ├─┬ axios@0.12.0 
  │ └─┬ follow-redirects@0.0.7 
  │   ├─┬ debug@2.6.9 
  │   │ └── ms@2.0.0 
  │   └── stream-consume@0.1.1 
  ├── bluebird@3.5.1 
  ├── es6-promise@3.3.1 
  ├── event-source-polyfill@0.0.7 
  ├─┬ eventsource@0.2.3 
  │ └─┬ original@1.0.0 
  │   └─┬ url-parse@1.0.5 
  │     ├── querystringify@0.0.4 
  │     └── requires-port@1.0.0 
  ├── lodash@4.17.5 
  ├─┬ stellar-base@0.7.7 
  │ ├── base32.js@0.1.0 
  │ ├── bignumber.js@4.1.0 
  │ ├── crc@3.5.0 
  │ ├─┬ ed25519@0.0.4 
  │ │ ├── bindings@1.3.0 
  │ │ └── nan@2.9.2 
  │ ├─┬ js-xdr@1.0.2 
  │ │ ├─┬ babel-runtime@4.7.16 
  │ │ │ └── core-js@0.6.1 
  │ │ ├── cursor@0.1.5 
  │ │ ├── lodash@3.10.1 
  │ │ ├── long@2.4.0 
  │ │ └── sequencify@0.0.7 
  │ ├─┬ sha.js@2.4.10 
  │ │ ├── inherits@2.0.3 
  │ │ └── safe-buffer@5.1.1 
  │ └── tweetnacl@0.14.5 
  ├── toml@2.3.3 
  └── urijs@1.18.4
```

**Comment by patrickxb** [comment]
We can convert on the go side.

**Comment by patrickxb** [comment]
(from stellar to kid)

**Comment by mlsteele** [comment]
We'll probably want more than one per account. So throw in a `"name": "default"` or something.

Some reasons to have multiple.
- You lose your secret and want to roll and move your assets.
- To claim a hardware wallet.
- Multisig (which would use this secret key distribution model, but probably could use this link)

**Comment by patrickxb** [comment]
Could we use a different word than 'currency' for the wallet type?

**Comment by maxtaco** [comment]
Ok here's the latest:

```json
{
  "body": {
    "key": {
      "host": "keybase.io",
      "kid": "01207ce870c29fad0774b62951a5022395b20b46e98b401979cd887f2e3e5dc3766d0a",
      "uid": "53288f5e98318ac31e389eb36136f54e",
      "username": "u_525d500915"
    },
    "type": "wallet",
    "version": 1,
    "wallet": {
      "account_name": "default",
      "address": "GB6VPV6GFUIP76LXXVUHATPUJQPCYMWUV3TLTHYK5RASCZ5UXAR66DMV",
      "network": "stellar"
    },
    "wallet_key": {
      "kid": "01207d57d7c62d10fff977bd68704df44c1e2c32d4aee6b99f0aec412167b4b823ef0a",
      "reverse_sig": "g6Rib2R5hqhkZXRhY2hlZMOpaGFzaF90eXBlCqNrZXnEIwEgfVfXxi0Q//l3vWhwTfRMHiwy1K7muZ8K7EEhZ7S4I+8Kp3BheWxvYWTFAiB7ImJvZHkiOnsia2V5Ijp7Imhvc3QiOiJrZXliYXNlLmlvIiwia2lkIjoiMDEyMDdjZTg3MGMyOWZhZDA3NzRiNjI5NTFhNTAyMjM5NWIyMGI0NmU5OGI0MDE5NzljZDg4N2YyZTNlNWRjMzc2NmQwYSIsInVpZCI6IjUzMjg4ZjVlOTgzMThhYzMxZTM4OWViMzYxMzZmNTRlIiwidXNlcm5hbWUiOiJ1XzUyNWQ1MDA5MTUifSwidHlwZSI6IndhbGxldCIsInZlcnNpb24iOjEsIndhbGxldCI6eyJhY2NvdW50X25hbWUiOiJkZWZhdWx0IiwiYWRkcmVzcyI6IkdCNlZQVjZHRlVJUDc2TFhYVlVIQVRQVUpRUENZTVdVVjNUTFRIWUs1UkFTQ1o1VVhBUjY2RE1WIiwibmV0d29yayI6InN0ZWxsYXIifSwid2FsbGV0X2tleSI6eyJraWQiOiIwMTIwN2Q1N2Q3YzYyZDEwZmZmOTc3YmQ2ODcwNGRmNDRjMWUyYzMyZDRhZWU2Yjk5ZjBhZWM0MTIxNjdiNGI4MjNlZjBhIiwicmV2ZXJzZV9zaWciOm51bGx9fSwiY3RpbWUiOjE1MjA2MTk0ODEsImV4cGlyZV9pbiI6MTU3NjgwMDAwLCJwcmV2IjpudWxsLCJzZXFfdHlwZSI6MSwic2Vxbm8iOjAsInRhZyI6InNpZ25hdHVyZSJ9o3NpZ8RAeF57Nro+GGUFykQG4FFcgtNPSH8q1vcn5UkH+0urIZCIKc3GTS4GA9vi5MwVB4Tlxv7LbipHFCY1B8GjvvlIBahzaWdfdHlwZSCjdGFnzQICp3ZlcnNpb24B"
    }
  },
  "ctime": 1520619481,
  "expire_in": 157680000,
  "prev": null,
  "seq_type": 1,
  "seqno": 0,
  "tag": "signature"
}
```

**Comment by patrickxb** [comment]
So what happens in 5 years when it expires?

**Comment by maxtaco** [comment]
This library isn't actually generating sigs anymore on the critical path, so nothing. It's all about what the clients put there.

**Comment by maxtaco** [comment]
@patrickxb  ok to ship it?  we can always change it until it's actually in the sigchain

**Comment by maxtaco** [comment]
Merged with this:

```json
{
  "body": {
    "key": {
      "host": "keybase.io",
      "kid": "01207ce870c29fad0774b62951a5022395b20b46e98b401979cd887f2e3e5dc3766d0a",
      "uid": "53288f5e98318ac31e389eb36136f54e",
      "username": "u_525d500915"
    },
    "type": "wallet",
    "version": 1,
    "wallet": {
      "name": "default",
      "address": "GB6VPV6GFUIP76LXXVUHATPUJQPCYMWUV3TLTHYK5RASCZ5UXAR66DMV",
      "network": "stellar"
    },
    "wallet_key": {
      "kid": "01207d57d7c62d10fff977bd68704df44c1e2c32d4aee6b99f0aec412167b4b823ef0a",
      "reverse_sig": "g6Rib2R5hqhkZXRhY2hlZMOpaGFzaF90eXBlCqNrZXnEIwEgfVfXxi0Q//l3vWhwTfRMHiwy1K7muZ8K7EEhZ7S4I+8Kp3BheWxvYWTFAiB7ImJvZHkiOnsia2V5Ijp7Imhvc3QiOiJrZXliYXNlLmlvIiwia2lkIjoiMDEyMDdjZTg3MGMyOWZhZDA3NzRiNjI5NTFhNTAyMjM5NWIyMGI0NmU5OGI0MDE5NzljZDg4N2YyZTNlNWRjMzc2NmQwYSIsInVpZCI6IjUzMjg4ZjVlOTgzMThhYzMxZTM4OWViMzYxMzZmNTRlIiwidXNlcm5hbWUiOiJ1XzUyNWQ1MDA5MTUifSwidHlwZSI6IndhbGxldCIsInZlcnNpb24iOjEsIndhbGxldCI6eyJhY2NvdW50X25hbWUiOiJkZWZhdWx0IiwiYWRkcmVzcyI6IkdCNlZQVjZHRlVJUDc2TFhYVlVIQVRQVUpRUENZTVdVVjNUTFRIWUs1UkFTQ1o1VVhBUjY2RE1WIiwibmV0d29yayI6InN0ZWxsYXIifSwid2FsbGV0X2tleSI6eyJraWQiOiIwMTIwN2Q1N2Q3YzYyZDEwZmZmOTc3YmQ2ODcwNGRmNDRjMWUyYzMyZDRhZWU2Yjk5ZjBhZWM0MTIxNjdiNGI4MjNlZjBhIiwicmV2ZXJzZV9zaWciOm51bGx9fSwiY3RpbWUiOjE1MjA2MTk0ODEsImV4cGlyZV9pbiI6MTU3NjgwMDAwLCJwcmV2IjpudWxsLCJzZXFfdHlwZSI6MSwic2Vxbm8iOjAsInRhZyI6InNpZ25hdHVyZSJ9o3NpZ8RAeF57Nro+GGUFykQG4FFcgtNPSH8q1vcn5UkH+0urIZCIKc3GTS4GA9vi5MwVB4Tlxv7LbipHFCY1B8GjvvlIBahzaWdfdHlwZSCjdGFnzQICp3ZlcnNpb24B"
    }
  },
  "ctime": 1520619481,
  "expire_in": 157680000,
  "prev": null,
  "seq_type": 1,
  "seqno": 0,
  "tag": "signature"
}
```

**Pull request merged**
