### PR TITLE
Update wot schema

### PR DESCRIPTION
**Pull request by mlsteele**
Using sig IDs will make it easier for server, service, and gui to communicate. Fewer fields to validate and fill in.

It means more work to present the state of the vouchee's proofs at the time of vouching. But there is no plan for that, "rest of the proofs [from failing_proofs] are assumed to be working" means that's true anyway, and it's nice not to trust A about the details of user B's proof.

### CODE REVIEW

**Comment by patrickxb** [comment]
Using sig ids looks good to me, but want to make sure @maxtaco agrees.

**Comment by maxtaco** [comment]
If this isn't a schema for SigIDs, can you make one?

**Comment by maxtaco** [comment]
(and use it)

**Comment by maxtaco** [comment]
Also, why are the other fields disappearing?

**Comment by maxtaco** [comment]
Oh, I think I remember what I was thinking here. Wasn't there a screenshot where you got to say **which** of the proofs you thought were useful to you, which is why some of them are listed?

**Comment by mlsteele** [comment]
Back to thick proofs. But flattened.

**Pull request merged**
